# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InvestLog' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InvestLog
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Firebase/Database'
  pod 'lottie-ios'
  pod 'SnapKit', '~> 4.0'
  pod 'KeychainSwift', '~> 15.0'
  
  target 'InvestLogTests' do
    inherit! :complete
  end
  
end


